-- DBS, Project

-- Task 1, Make the following creates:
-- Creates für: Land,Ort,Anschrift,Verein,Match,Liga,Mannschaft,

CREATE TABLE "LAND" 
   (	"LAND_ID" NUMBER, 
	"KENNZEICHEN" VARCHAR2(20), 
	"BEZEICHNUNG" VARCHAR2(255)
   ) ;
   
CREATE TABLE "ORT" 
   (	"PLZ" NUMBER, 
	"LAND_ID" NUMBER, --fk
	"BEZEICHNUNG" VARCHAR2(255)
   ) ;

CREATE TABLE "ANSCHRIFT" 
   (	"ANSCHRIFTID_PK" NUMBER, 
	"PLZ" NUMBER, --fk
	"BEZEICHNUNG" VARCHAR2(255)
   ) ;
   
CREATE TABLE "VEREIN"
  ( "VERINID_PK" NUMBER,
  "ANSCHRIFTID_PK" NUMBER, --fk
  "NAME" VARCHAR2(255)
  ) ;

CREATE TABLE "LIGA"
  ( "LIGAID_PK" NUMBER,
  "DATUM_BEGONNEN" DATE,
  "DATUM_GEENDET" DATE,
  "NAME" VARCHAR2(255),
  "ALTERSGRUPPE" VARCHAR2(255)
  );  

CREATE TABLE "MANNSCHAFT_MATCH"
  ( "MATCHID_PK" NUMBER,
  "MANNSCHAFTID_PK" NUMBER,
  "SPIELT_ALS" VARCHAR(4) --HEIM/GAST
  );

-- CREATE MANNSCHAFT_TRAINER
-- CREATE MATCH_SHIEDSRICHTER

CREATE TABLE "MATCH"
  ( "MATCHID_PK" NUMBER,
  "ANSCHRIFTID_PK" NUMBER, --fk
  "MANNSCHAFT_MATCH_PK" NUMBER, -- fk
  "LIGAID_PK" NUMBER, --fk
  "DATUM" DATE,
  "BEGONNEN_UM" TIMESTAMP,
  "GEENDET_UM" TIMESTAMP,
  "TORE_STAND" VARCHAR2(7), -- "nnn/nnn" || "n/n"
  "ALTERSGRUPPE" VARCHAR2(255)
  ) ;
  
CREATE TABLE "MANSCHAFT"
  ( "MANNSCHAFTID_PK" NUMBER,
  "VERINID_PK" NUMBER, --fk
  "MANNSCHAFT_MATCH_PK" NUMBER, --
  "NAME" VARCHAR2(255),
  "ALTERSGRUPPE" VARCHAR2(255)
  ) ;
  
-- CREATE SPIELER
-- CREATE TRAINER
-- CREATE SCHIEDSRICHTER
-- CREATE MITARBEITER_VORGESETZER
-- CREATE MITARBEITER
-- CREATE PERSON

  
