
DROP TABLE "LAND" CASCADE CONSTRAINTS;
DROP TABLE "ORT" CASCADE CONSTRAINTS;
DROP TABLE "ANSCHRIFT" CASCADE CONSTRAINTS;
DROP TABLE "VEREIN" CASCADE CONSTRAINTS;
DROP TABLE "LIGA" CASCADE CONSTRAINTS;
DROP TABLE "MANNSCHAFT_MATCH" CASCADE CONSTRAINTS;
DROP TABLE "MANNSCHAFT_TRAINER" CASCADE CONSTRAINTS;
DROP TABLE "MATCH_SCHIEDSRICHTER" CASCADE CONSTRAINTS;
DROP TABLE "MATCH" CASCADE CONSTRAINTS;
DROP TABLE "MANNSCHAFT" CASCADE CONSTRAINTS;
DROP TABLE "SPIELER" CASCADE CONSTRAINTS;
DROP TABLE "TRAINER" CASCADE CONSTRAINTS;
DROP TABLE "SCHIEDSRICHTER" CASCADE CONSTRAINTS;
DROP TABLE "MITARBEITER_VORGESETZTER" CASCADE CONSTRAINTS;
DROP TABLE "MITARBEITER" CASCADE CONSTRAINTS;
DROP TABLE "PERSON" CASCADE CONSTRAINTS;






  

  


   
