

DROP TABLE "ANSCHRIFT" CASCADE CONSTRAINTS;
DROP TABLE "ORT" CASCADE CONSTRAINTS;
DROP TABLE "LAND" CASCADE CONSTRAINTS;
DROP TABLE "MANSCHAFT" CASCADE CONSTRAINTS;
DROP TABLE "MATCH" CASCADE CONSTRAINTS;
DROP TABLE "MANNSCHAFT_MATCH" CASCADE CONSTRAINTS;
DROP TABLE "LIGA" CASCADE CONSTRAINTS;
DROP TABLE "VEREIN" CASCADE CONSTRAINTS;






  

  


   
