-------------Person-----------

REM 1. INSERTING into PERSON
SET DEFINE OFF;
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (1,1,"Camilla","Terry","10.05.80");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (2,2,"Price","Rollins","16.02.99");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (3,3,"Timon","Morris","11.05.71");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (4,4,"Fuller","Dale","30.12.79");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (5,5,"Garrison","Rodriquez","05.07.70");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (6,6,"Nadine","Potts","11.12.90");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (7,7,"Kitra","Powers","14.11.75");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (8,8,"Jayme","Copeland","17.07.95");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (9,9,"Kyle","Raymond","27.06.74");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (10,10,"Sheila","Neal","30.10.98");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (11,11,"Philip","Neal","18.09.89");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (12,12,"Genevieve","Clements","15.06.88");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (13,13,"Zephr","Lowery","09.10.89");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (14,14,"Lillian","Acosta","26.07.97");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (15,15,"Harding","Kane","15.05.71");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (16,16,"Craig","Odonnell","27.02.82");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (17,17,"Leandra","Richmond","11.09.94");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (18,18,"Brooke","Copeland","02.04.71");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (19,19,"Carly","Sykes","15.01.70");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (20,20,"Silas","Dorsey","25.08.90");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (21,21,"Shad","James","07.03.75");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (22,22,"Sonia","Vaughn","02.07.85");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (23,23,"Ulysses","Solomon","10.07.81");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (24,24,"Erich","Wade","23.01.82");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (25,25,"Kato","Rivers","02.03.89");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (26,26,"Amanda","Humphrey","06.03.80");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (27,27,"Otto","Le","29.10.95");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (28,28,"Neve","Cameron","06.02.76");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (29,29,"Zia","Pate","17.02.87");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (30,30,"Sophia","Logan","19.10.85");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (31,31,"Camden","Lawrence","14.02.97");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (32,32,"Adrian","Aguirre","31.01.77");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (33,33,"Grace","Gallagher","18.10.90");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (34,34,"Martin","Whitfield","20.01.77");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (35,35,"Elmo","Browning","28.11.96");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (36,36,"Christopher","Hughes","29.10.93");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (37,37,"Richard","Brock","17.11.87");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (38,38,"Paloma","Quinn","28.06.88");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (39,39,"Paula","Sloan","26.06.74");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (40,40,"Piper","Saunders","14.09.75");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (41,41,"Kelly","Conway","12.09.74");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (42,42,"Wyoming","Carroll","26.03.97");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (43,43,"Griffith","Conrad","01.02.71");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (44,44,"Leroy","Bates","13.08.83");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (45,45,"Kenyon","Summers","26.05.96");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (46,46,"Demetria","Bradley","01.12.93");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (47,47,"Jayme","Melton","12.06.76");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (48,48,"Veronica","Nielsen","12.11.93");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (49,49,"Donna","Mckinney","29.03.87");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (50,50,"Darryl","Grimes","20.08.91");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (51,51,"Lacota","Collins","29.12.71");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (52,52,"Kelsey","Vazquez","25.12.79");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (53,53,"Thaddeus","Patel","09.09.92");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (54,54,"Kristen","Mullen","04.05.97");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (55,55,"Madaline","Keith","14.08.77");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (56,56,"Isaiah","Wheeler","25.01.77");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (57,57,"Winter","Hampton","23.04.88");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (58,58,"Dolan","Knapp","03.08.79");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (59,59,"Jesse","Barry","03.11.74");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (60,60,"Avram","Burke","10.08.86");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (61,61,"Leigh","Acosta","27.07.77");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (62,62,"Rooney","Turner","03.07.85");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (63,63,"Brenna","Mcgowan","30.05.86");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (64,64,"Bernard","Soto","23.10.97");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (65,65,"Salvador","Strong","14.04.74");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (66,66,"Carl","Harrington","06.11.71");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (67,67,"Fleur","Pate","01.12.94");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (68,68,"Nayda","Dillard","03.02.87");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (69,69,"Orlando","Holloway","03.10.87");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (70,70,"Tarik","Mosley","09.08.82");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (71,71,"Joshua","Black","23.02.86");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (72,72,"Yael","Morton","24.11.00");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (73,73,"Fitzgerald","Jenkins","04.02.82");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (74,74,"Acton","Robertson","31.03.98");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (75,75,"Lacy","Zamora","26.06.97");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (76,76,"Lionel","Blair","16.01.75");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (77,77,"Carolyn","Holt","13.05.83");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (78,78,"Beck","Greer","09.07.82");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (79,79,"Yoko","Hancock","23.02.98");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (80,80,"Matthew","Warner","22.05.76");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (81,81,"Hillary","Carson","18.07.83");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (82,82,"Catherine","Contreras","03.07.72");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (83,83,"Samuel","Rivas","05.08.71");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (84,84,"Jennifer","Cotton","12.03.91");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (85,85,"Rina","Kerr","24.01.81");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (86,86,"Paloma","Walsh","27.03.98");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (87,87,"Dean","Joyce","02.12.97");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (88,88,"Camille","Chambers","23.05.76");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (89,89,"Mercedes","Marquez","24.08.80");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (90,90,"Nora","Roberts","18.08.94");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (91,91,"Ira","Roberson","21.06.99");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (92,92,"Zane","Lara","10.08.85");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (93,93,"Tamara","Bartlett","12.06.70");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (94,94,"Susan","Bean","27.10.77");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (95,95,"Vera","Everett","29.07.90");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (96,96,"Veronica","Justice","06.11.81");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (97,97,"Yoshi","Cole","19.12.72");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (98,98,"Neil","Le","18.07.97");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (99,99,"Lacey","Mays","10.06.95");
INSERT INTO `Person` (`personID`,`anschriftID_fk`,`vname`,`nname`,`geburtsdatum`) VALUES (100,100,"Amena","Moran","03.09.97");

-------------Spieler-----------

REM 2. INSERTING into Spieler
SET DEFINE OFF;
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (1,1,"05.08.19",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (2,2,"01.09.16","26.06.19");
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (3,3,"15.04.19",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (4,4,"09.06.16",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (5,5,"07.05.17","18.02.19");
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (6,6,"10.08.17",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (7,7,"04.07.19","08.10.20");
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (8,8,"18.03.19",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (9,9,"20.05.18",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (10,10,"14.11.17",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (11,11,"29.05.18",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (12,12,"07.12.15",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (13,13,"13.03.17",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (14,14,"24.04.19",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (15,15,"09.04.18","15.10.20");
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (16,16,"23.06.19",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (17,17,"11.10.17",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (18,18,"02.06.18",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (19,19,"16.06.17","17.11.19");
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (20,20,"06.04.18",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (21,21,"02.11.16",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (22,22,"14.03.18","26.11.19");
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (23,23,"30.10.19",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (24,24,"15.03.16",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (25,25,"05.12.15","25.05.20");
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (26,26,"08.11.16",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (27,27,"15.07.19",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (28,28,"16.09.17",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (29,29,"12.05.16",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (30,30,"05.07.16","15.01.20");
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (31,31,"18.07.17",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (32,32,"18.01.19",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (33,33,"22.10.18",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (34,34,"01.07.19",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (35,35,"16.01.18",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (36,36,"02.07.17",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (37,37,"01.07.16",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (38,38,"12.09.18",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (39,39,"07.11.16",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (40,40,"06.08.17",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (41,41,"22.12.15","29.03.20");
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (42,42,"24.09.18",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (43,43,"21.04.18",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (44,44,"25.04.17",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (45,45,"07.01.19",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (46,46,"09.03.18",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (47,47,"07.12.16","17.03.20");
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (48,48,"03.08.18",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (49,49,"02.01.18",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (50,50,"26.06.19","14.06.19");
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (51,51,"09.07.18",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (52,52,"04.12.18",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (53,53,"25.11.15",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (54,54,"30.04.16",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (55,55,"25.05.16",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (56,56,"26.06.19",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (57,57,"29.05.18",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (58,58,"11.05.17",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (59,59,"19.09.19",NULL);
INSERT INTO `Spieler` (`spielerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (60,60,"21.11.15",NULL);

-------------Trainer-----------

REM 3. INSERTING into Trainer
SET DEFINE OFF;
INSERT INTO `Trainer` (`trainerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (1,61,"01.12.15","27.02.16");
INSERT INTO `Trainer` (`trainerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (2,62,"23.02.16",NULL);
INSERT INTO `Trainer` (`trainerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (3,63,"20.12.15",NULL);
INSERT INTO `Trainer` (`trainerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (4,64,"29.02.16",NULL);
INSERT INTO `Trainer` (`trainerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (5,65,"14.05.16",NULL);
INSERT INTO `Trainer` (`trainerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (6,66,"27.08.17",NULL);
INSERT INTO `Trainer` (`trainerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (7,67,"10.11.15","13.05.20");
INSERT INTO `Trainer` (`trainerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (8,68,"24.01.19",NULL);
INSERT INTO `Trainer` (`trainerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (9,69,"02.11.18",NULL);
INSERT INTO `Trainer` (`trainerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (10,70,"04.01.19",NULL);
INSERT INTO `Trainer` (`trainerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (11,71,"08.10.16",NULL);
INSERT INTO `Trainer` (`trainerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (12,72,"14.01.16",NULL);
INSERT INTO `Trainer` (`trainerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (13,73,"23.05.19",NULL);
INSERT INTO `Trainer` (`trainerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (14,74,"22.09.17","16.05.20");
INSERT INTO `Trainer` (`trainerID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (15,75,"13.07.19",NULL);

-------------schiedsrichter -----------

REM 4. INSERTING into schiedsrichter
SET DEFINE OFF;
INSERT INTO `schiedsrichter` (`schiedsrichterID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (1,76,"07.06.17",NULL);
INSERT INTO `schiedsrichter` (`schiedsrichterID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (2,77,"23.04.18","06.06.20");
INSERT INTO `schiedsrichter` (`schiedsrichterID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (3,78,"25.09.17",NULL);
INSERT INTO `schiedsrichter` (`schiedsrichterID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (4,79,"26.11.16",NULL);
INSERT INTO `schiedsrichter` (`schiedsrichterID`,`personID_fk`,`eintrittsdatum`,`austrittsdatum`) VALUES (5,80,"29.06.18",NULL);

-------------mitarbeiter -----------

REM 5. INSERTING into mitarbeiter
SET DEFINE OFF;
INSERT INTO `mitarbeiter` (`mitarbeiterID`,`personID_fk`,`funktion`,`eintrittsdatum`,`austrittsdatum`) VALUES (1,81,"augue","08.02.18",NULL);
INSERT INTO `mitarbeiter` (`mitarbeiterID`,`personID_fk`,`funktion`,`eintrittsdatum`,`austrittsdatum`) VALUES (2,82,"arcu.","11.05.17",NULL);
INSERT INTO `mitarbeiter` (`mitarbeiterID`,`personID_fk`,`funktion`,`eintrittsdatum`,`austrittsdatum`) VALUES (3,83,"non","11.11.18","01.10.19");
INSERT INTO `mitarbeiter` (`mitarbeiterID`,`personID_fk`,`funktion`,`eintrittsdatum`,`austrittsdatum`) VALUES (4,84,"vitae","11.08.19",NULL);
INSERT INTO `mitarbeiter` (`mitarbeiterID`,`personID_fk`,`funktion`,`eintrittsdatum`,`austrittsdatum`) VALUES (5,85,"consequat","24.03.16",NULL);
INSERT INTO `mitarbeiter` (`mitarbeiterID`,`personID_fk`,`funktion`,`eintrittsdatum`,`austrittsdatum`) VALUES (6,86,"condimentum","05.05.16",NULL);
INSERT INTO `mitarbeiter` (`mitarbeiterID`,`personID_fk`,`funktion`,`eintrittsdatum`,`austrittsdatum`) VALUES (7,87,"Pellentesque","25.02.18",NULL);
INSERT INTO `mitarbeiter` (`mitarbeiterID`,`personID_fk`,`funktion`,`eintrittsdatum`,`austrittsdatum`) VALUES (8,88,"mollis","15.07.18",NULL);
INSERT INTO `mitarbeiter` (`mitarbeiterID`,`personID_fk`,`funktion`,`eintrittsdatum`,`austrittsdatum`) VALUES (9,89,"hendrerit.","11.02.16","28.07.20");
INSERT INTO `mitarbeiter` (`mitarbeiterID`,`personID_fk`,`funktion`,`eintrittsdatum`,`austrittsdatum`) VALUES (10,90,"at,","13.03.18",NULL);
INSERT INTO `mitarbeiter` (`mitarbeiterID`,`personID_fk`,`funktion`,`eintrittsdatum`,`austrittsdatum`) VALUES (11,91,"Integer","24.10.18",NULL);
INSERT INTO `mitarbeiter` (`mitarbeiterID`,`personID_fk`,`funktion`,`eintrittsdatum`,`austrittsdatum`) VALUES (12,92,"volutpat","05.10.17",NULL);
INSERT INTO `mitarbeiter` (`mitarbeiterID`,`personID_fk`,`funktion`,`eintrittsdatum`,`austrittsdatum`) VALUES (13,93,"nec","05.09.19",NULL);
INSERT INTO `mitarbeiter` (`mitarbeiterID`,`personID_fk`,`funktion`,`eintrittsdatum`,`austrittsdatum`) VALUES (14,94,"conubia","13.11.15",NULL);
INSERT INTO `mitarbeiter` (`mitarbeiterID`,`personID_fk`,`funktion`,`eintrittsdatum`,`austrittsdatum`) VALUES (15,95,"adipiscing","24.08.18",NULL);
INSERT INTO `mitarbeiter` (`mitarbeiterID`,`personID_fk`,`funktion`,`eintrittsdatum`,`austrittsdatum`) VALUES (16,96,"ridiculus","20.11.18","04.10.20");
INSERT INTO `mitarbeiter` (`mitarbeiterID`,`personID_fk`,`funktion`,`eintrittsdatum`,`austrittsdatum`) VALUES (17,97,"libero","30.10.19",NULL);
INSERT INTO `mitarbeiter` (`mitarbeiterID`,`personID_fk`,`funktion`,`eintrittsdatum`,`austrittsdatum`) VALUES (18,98,"imperdiet,","10.02.16",NULL);
INSERT INTO `mitarbeiter` (`mitarbeiterID`,`personID_fk`,`funktion`,`eintrittsdatum`,`austrittsdatum`) VALUES (19,99,"orci","26.02.18",NULL);
INSERT INTO `mitarbeiter` (`mitarbeiterID`,`personID_fk`,`funktion`,`eintrittsdatum`,`austrittsdatum`) VALUES (20,100,"consequat","04.07.16",NULL);